name: "PR"

on:
  pull_request:

env:
  INT_ACCOUNT_ID: 12345
  INT_NON_PROD_ACCOUNT_ID: 56789
  INT_PROD_ACCOUNT_ID: 99999

permissions:
  id-token: write
  contents: read
  pull-requests: read
  checks: write

jobs:
  run-tf-plan:
    name: "Run TF Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
    
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: |
              trap 'exit_code="$?"; echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"; if [[ "$exit_code" == "2" ]]; then exit 0; fi' EXIT
              terraform plan -detailed-exitcode
              
      - name: Act on Terraform Exit Code
        run: |
          echo "Exit code was ${{ steps.plan.outputs.exit_code }}"
          if [[ "${{ steps.plan.outputs.exit_code }}" == "2" ]]; then
            echo "Terraform detected changes!"
          elif [[ "${{ steps.plan.outputs.exit_code }}" == "0" ]]; then
            echo "No changes."
          else
            echo "Terraform plan failed!"
            exit 1
          fi
